### ISSUE TITLE
Establish issue labels

### ISSUE THREAD

**Issue by severndb** [severndb/structure#18]
# Aim

* Enumerate issue labels.
* Establish assigned color for each label.
* Document everything for reference.

**Comment by severndb** [comment]
Adopted labels:

* `bug` - red. Bugs.
* `writ` - black. Related to legal systems.
* `vision` - light purple. Description of an envisioned result. Issue title expresses the result in present tense.

**Comment by severndb** [comment]
Possible labels:

* `horizon` - Something on or over the horizon. Not in easy reach.
* `clarify` - Clarification needed. For eg bug reports without sufficient information.
* `reproduced` - white. Reported issue successfully reproduced. White to indicate clear, no new clarification needed.
* `bounty` - Bounty open for the issue.
* `feature` - Description of a new feature.
* `enhance` - Description of an enhancement to an existing feature.
* `optimize` - Description of an optimization of an existing feature.
* `duplicate` - Duplicate report of an issue. Closed with link to canonical issue.
* `nonsense` - Nonsensical or corrupted issue.

**Comment by severndb** [comment]
Possible labels:

* `document` - Task to produce or alter documentation.
* `model` - Task to produce or alter a model.
* `convention` - Establishment of a convention.

**Comment by severndb** [comment]
Possible label:

* `module` - Description of a new module.

**Comment by severndb** [comment]
Possible label:

* `external` - Belongs in a different repository. Closed with link to canonical issue.

**Comment by gowpen** [comment]
Possible label:

* `support` - Support question. Closed with reference to support resources.

**Comment by gowpen** [comment]
List of labels established:
https://github.com/severndb/structure/wiki/Labels
